### ISSUE TITLE
Installing Plugins currently only via file copy to persistent storage

### ISSUE THREAD

**Issue by MoergJ** [itzg/minecraft-server-charts#34]
**Feature proposal**
Add the functionality to configure a list (list of downloadUrls, or even Spigot Plugin names, tbd) of Pugins, that are downloaded and stored to the correct directory before starting the minecraft server.

**Input appreciated**
I currently don't know how the URLs for downloading plugin jars on spigot can be used, as the URLs are not leading to the file directly. I thought of a solution based on this: https://github.com/InventivetalentDev/SpigetDownloader

I will look into this this evening and try to provide a PR.

**Comment by itzg** [comment]
This is a great idea, but I don't think it belongs in the helm chart. It would be a feature to add to the image itself, https://github.com/itzg/docker-minecraft-server.  

However, I have had to abandon various plugin and modpack download features since the provider websites have blocked with ad pages or complex CDN URLs. Good luck finding a robust solution.
