### ISSUE TITLE
CURSEFORGE support?

### ISSUE THREAD

**Issue by Blackphidora** [itzg/minecraft-server-charts#44]
Howdy, Is Curseforge support possible? One of the main issues of the normal container is that the modpack file needs to be downloaded and preloaded with TYPE=CURSEFORGE and CF_SERVER_MOD within the container's filesystem.

Perhaps, part of the template is to generate a job or cronjob that could wget a file specified by the helm chart, The container should continue to fallback untill the modpack zip is downloaded.

Any additional input? Still rather new to k8s and helm charts in general.

**Comment by itzg** [comment]
There's a couple of ways this is already supported:

- The Helm chart itself provides [a "hook" for declaring any init containers](https://github.com/itzg/minecraft-server-charts/blob/master/charts/minecraft/values.yaml#L46-L54) you want, which would be an ideal place to pre-download things into the data volume.
- The `CF_SERVER_MOD` in [the image itself](https://github.com/itzg/docker-minecraft-server) actually does accept a URL for downloading modpack; however, I had to stop advertising that feature since Twitch, CurseForge, etc websites all started "blocking" automated (curl and wget) downloads by inserting ad link pages, CDN session handoff, etc.

**Comment by Blackphidora** [comment]
@itzg That is good to know, does `CF_SERVER_MOD` support any HTTP(S) endpoint or does it assume and fill in for CurseForge's download URI? if it does I can host the file myself and no change would be needed.

**Comment by itzg** [comment]
It uses the URL as given, so can be either http or https. It should skip over some curse/FTB logic it has in the case of a self hosted URL.

**Comment by Blackphidora** [comment]
:+1:  I got this to work,

Only thing I would suggest is adding a start probe, some modpacks can take up for 10 mins to boot on init install. 

Thank you!
/close
