### ISSUE TITLE
Setting motd in values of minecraft chart doesn't override default motd

### ISSUE THREAD

**Issue by AlexPresso** [itzg/minecraft-server-charts#92]
Hey there,
Setting the server motd in a `values.yml` file doesn't override the Docker image motd:
```
...
minecraftServer:
...
   motd: "Test"
...
```
Installation command: `helm install -f values.yml --namespace test --create-namespace minecraft itzg/minecraft`
Result:
![Sans titre](https://user-images.githubusercontent.com/15526962/148701986-3ee7bd6f-867a-45bb-baa9-81fece06ddd1.png)

**Comment by itzg** [comment]
Can you try something for me? Try adding `OVERRIDE_SERVER_PROPERTIES: "true"` to `extraEnv` and see if that ensures the properties file gets the intended value. I am considering making that the default but also exposing a specific helm value for it.

**Comment by AlexPresso** [comment]
Yes, everything working with `OVERRIDE_SERVER_PROPERTIES`

**Comment by merkinbob** [comment]
I can add this as a fully supported value btw, instead of using extraEnv

**Comment by merkinbob** [comment]
you can assign this to me

**Comment by SavePointSam** [comment]
I am hitting this issue on latest. I've tried destroying my PV and setting `OVERRIDE_SERVER_PROPERTIES` true. No matter what I do, the motd is always "A Minecraft Server powered by Docker"

**Comment by SavePointSam** [comment]
I was able to solve my issues.

It turns out my line break was being converted to a newline before being passed to `mc-image-helper asciify` which then defaulted away on failure. To get a newline in your MOTD. be sure to escape your newline in values.yaml (`\n` -> `\\n`).

I also had difficulties getting the right section character. Be sure to use `§`.

Everything is working great now!
